default_platform :ios
fastlane_require 'colorize'
fastlane_version "2.64.0"

platform :ios do

  # --------------------------------------------------
  # Set Up & Tear Down
  # --------------------------------------------------

  before_all do |lane, options|
  end

  after_all do |lane, options|
  end

  # --------------------------------------------------
  # Lanes
  # --------------------------------------------------

  import "lanes/playground.rb"

  # --------------------------------------------------
  # Error Handling
  # --------------------------------------------------

  error do |lane, exception, options|
  end

end
